# Generated by Django 4.1.1 on 2022-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_address_state_alter_address_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="rio de janeiro", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="map_image",
            field=models.CharField(default="na", max_length=250),
            preserve_default=False,
        ),
    ]
