# Generated by Django 4.1.1 on 2023-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0004_address_address2_address_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="street",
            new_name="address1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="number",
        ),
        migrations.AlterField(
            model_name="address",
            name="address2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
