# Generated by Django 4.1.1 on 2023-06-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "addresses",
            "0005_rename_street_address_address1_remove_address_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="Canada", max_length=30),
        ),
    ]
