# Generated by Django 4.1.1 on 2023-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0006_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=30),
        ),
    ]
