# Generated by Django 4.1.1 on 2023-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0007_alter_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="timezone",
            field=models.CharField(default="America/Vancouver", max_length=40),
        ),
    ]
