# Generated by Django 4.1.1 on 2023-06-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0008_address_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="timezone",
            field=models.CharField(max_length=40),
        ),
    ]
