services:
  db:
    image: postgres
    env_file: .env
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    env_file: .env
    volumes:
      - .:/code
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    depends_on:
      - db

  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      # Files ignored with .dockerignore are replaced for the volume, allow hotreload
      - .:/code
    depends_on:
      - db
      - migration

volumes:
  pgdata:
