# Generated by Django 4.1.1 on 2023-06-23 17:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_alter_court_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonoperatingday",
            name="court",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_operating_days",
                to="courts.court",
            ),
        ),
        migrations.AlterField(
            model_name="nonoperatingday",
            name="regular_day_off",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("MONDAY", "Monday"),
                        ("TUESDAY", "Tuesday"),
                        ("WEDNESDAY", "Wednesday"),
                        ("THURSDAY", "Thursday"),
                        ("FRIDAY", "Friday"),
                        ("SATURDAY", "Saturday"),
                        ("SUNDAY", "Sunday"),
                    ],
                    default=list,
                    max_length=9,
                ),
                size=None,
            ),
        ),
    ]
