# Generated by Django 4.1.1 on 2023-01-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0003_address_city_address_map_image"),
        ("facilities", "0003_alter_facility_email_alter_facility_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility",
                to="addresses.address",
            ),
        ),
    ]
