# Generated by Django 4.1.1 on 2023-06-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0009_alter_address_timezone"),
        ("facilities", "0004_alter_facility_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility",
                to="addresses.address",
            ),
        ),
    ]
